apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: global-id-topic
  namespace: redhat-lab
  labels:
    strimzi.io/cluster: events-demo
spec:
  partitions: 3
  replicas: 3
  config:
    cleanup.policy: compact
