apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: service-registry-scram
  namespace: redhat-lab
spec:
  configuration:
    persistence: streams
    streams:
      applicationId: service-registry-scram
      bootstrapServers: events-demo-kafka-bootstrap.redhat-lab.svc:9093
      security:
        scram:
          user: service-registry-kafka-user-scram
          passwordSecretName: service-registry-kafka-user-scram
          truststoreSecretName: events-demo-cluster-ca-cert          
